FROM dokploy/dokploy:canary
COPY .next /app/.next
COPY public /app/public
COPY dist /app/dist
COPY ..final/../compose.js /app/node_modules/@dokploy/server/dist/utils/builders/compose.js
COPY ..final/../services-compose.js /app/node_modules/@dokploy/server/dist/services/compose.js
